FROM node:14.16.1-alpine

WORKDIR /usr/local/user-ms

COPY package.json .
COPY package-lock.json .

RUN npm install --silent --progress=false

COPY . .

EXPOSE 3000

ENTRYPOINT [ "npm", "run", "dev" ]